"""Stable error taxonomy for the controlled local A/B/C extension."""

from enum import StrEnum


class LocalABCFailureCode(StrEnum):
    """Machine-readable failures used by contracts, gates, and evidence ledgers."""

    ENVIRONMENT_UNSUPPORTED = "ENVIRONMENT_UNSUPPORTED"
    WORKER_START_FAILED = "WORKER_START_FAILED"
    MODEL_IDENTITY_MISMATCH = "MODEL_IDENTITY_MISMATCH"
    TOKENIZER_IDENTITY_MISMATCH = "TOKENIZER_IDENTITY_MISMATCH"
    PREFIX_HASH_MISMATCH = "PREFIX_HASH_MISMATCH"
    ROUTE_REALIZATION_MISMATCH = "ROUTE_REALIZATION_MISMATCH"
    CACHE_RESET_FAILED = "CACHE_RESET_FAILED"
    TELEMETRY_NOT_EXPOSED = "TELEMETRY_NOT_EXPOSED"
    TELEMETRY_NOT_OBSERVED = "TELEMETRY_NOT_OBSERVED"
    TELEMETRY_AMBIGUOUS = "TELEMETRY_AMBIGUOUS"
    TELEMETRY_INVALID = "TELEMETRY_INVALID"
    SESSION_INTERRUPTED = "SESSION_INTERRUPTED"
    RUN_INELIGIBLE = "RUN_INELIGIBLE"
