"""Stable error taxonomy for the controlled local A/B/C extension."""

from enum import StrEnum


class LocalABCFailureCode(StrEnum):
    """Machine-readable failures used by contracts, gates, and evidence ledgers."""

    ENVIRONMENT_UNSUPPORTED = "ENVIRONMENT_UNSUPPORTED"
    WORKER_START_FAILED = "WORKER_START_FAILED"
    MODEL_IDENTITY_MISMATCH = "MODEL_IDENTITY_MISMATCH"
    TOKENIZER_IDENTITY_MISMATCH = "TOKENIZER_IDENTITY_MISMATCH"
    PREFIX_HASH_MISMATCH = "PREFIX_HASH_MISMATCH"
    ROUTE_REALIZATION_MISMATCH = "ROUTE_REALIZATION_MISMATCH"
    CACHE_RESET_FAILED = "CACHE_RESET_FAILED"
    TELEMETRY_NOT_EXPOSED = "TELEMETRY_NOT_EXPOSED"
    TELEMETRY_NOT_OBSERVED = "TELEMETRY_NOT_OBSERVED"
    TELEMETRY_AMBIGUOUS = "TELEMETRY_AMBIGUOUS"
    TELEMETRY_INVALID = "TELEMETRY_INVALID"
    OUTPUT_JSON_INVALID = "OUTPUT_JSON_INVALID"
    OUTPUT_KEY_SET_MISMATCH = "OUTPUT_KEY_SET_MISMATCH"
    OUTPUT_ANSWER_MISMATCH = "OUTPUT_ANSWER_MISMATCH"
    OUTPUT_CASE_ID_MISMATCH = "OUTPUT_CASE_ID_MISMATCH"
    OUTPUT_TURN_INDEX_MISMATCH = "OUTPUT_TURN_INDEX_MISMATCH"
    OUTPUT_CONFIDENCE_MISMATCH = "OUTPUT_CONFIDENCE_MISMATCH"
    OUTPUT_EXTRA_TEXT = "OUTPUT_EXTRA_TEXT"
    OUTPUT_TRUNCATED = "OUTPUT_TRUNCATED"
    SESSION_INTERRUPTED = "SESSION_INTERRUPTED"
    RUN_INELIGIBLE = "RUN_INELIGIBLE"
