"""Typed boundary contracts for AuraGateway."""

from auragateway.contracts.chunking import (
    ChunkingCandidateStatus,
    ChunkingConfiguration,
    ChunkingManifest,
    ChunkingRunSummary,
    ChunkingStrategy,
    CorpusChunk,
    SourceChunkCount,
)
from auragateway.contracts.corpus import (
    CorpusInventory,
    CorpusMinimumRequirements,
    CorpusSource,
    CorpusValidationSummary,
    DataClassification,
    DocumentCompleteness,
    DocumentFormat,
    DocumentStatus,
)
from auragateway.contracts.corpus_freeze import (
    CorpusArtifactRecord,
    CorpusDocumentHeader,
    CorpusFreezeRecord,
    CorpusFreezeStatus,
    CorpusFreezeSummary,
    CorpusSourceManifest,
)
from auragateway.contracts.retrieval import (
    BM25TermContribution,
    RetrievalAlgorithm,
    RetrievalCandidateStatus,
    RetrievalConfiguration,
    RetrievalEvidenceHit,
    RetrievalEvidenceResult,
    RetrievalFilter,
    RetrievalHit,
    RetrievalIndexManifest,
    RetrievalQuery,
    RetrievalResult,
    RetrievalRunSummary,
    RetrievalSmokeQuerySet,
    StalePolicy,
)

__all__ = [
    "BM25TermContribution",
    "ChunkingCandidateStatus",
    "ChunkingConfiguration",
    "ChunkingManifest",
    "ChunkingRunSummary",
    "ChunkingStrategy",
    "CorpusArtifactRecord",
    "CorpusChunk",
    "CorpusDocumentHeader",
    "CorpusFreezeRecord",
    "CorpusFreezeStatus",
    "CorpusFreezeSummary",
    "CorpusInventory",
    "CorpusMinimumRequirements",
    "CorpusSource",
    "CorpusSourceManifest",
    "CorpusValidationSummary",
    "DataClassification",
    "DocumentCompleteness",
    "DocumentFormat",
    "DocumentStatus",
    "RetrievalAlgorithm",
    "RetrievalCandidateStatus",
    "RetrievalConfiguration",
    "RetrievalEvidenceHit",
    "RetrievalEvidenceResult",
    "RetrievalFilter",
    "RetrievalHit",
    "RetrievalIndexManifest",
    "RetrievalQuery",
    "RetrievalResult",
    "RetrievalRunSummary",
    "RetrievalSmokeQuerySet",
    "SourceChunkCount",
    "StalePolicy",
]
